defaults:
  - model_defaults # Inherit model_defaults arguments


# --------------------------
#         Model
# --------------------------
load_CBM: True
load_weights: True
model: 'pscbm' # Model's name
tag: 'pscbm' # Model's tag for wandb logging
concept_learning: 'hard' # Characteristics of concept bottleneck, either hard {0,1}, or soft logits ['hard', 'soft', 'cem']
# I will then also want to use CEM.
i_epochs: 100 # The number of epochs for which the covariance matrix is fine-tuned. These are many for now, I will observe, how many are actually needed.
validate_per_epoch: 20 # More frequent to observe the behaviour better

learning_rate: 0.0001 # Learning rate in the optimization
optimizer: 'adam' # Optimizer: ['sgd','adam']
decrease_every: 150 # Frequency of the learning rate decrease
lr_divisor: 2 # Rate of the learning rate decrease
weight_decay: 0 # Weight decay
train_batch_size: 64 # Batch size for the training set
val_batch_size: 64 # Batch size for the validation and test sets

# Covariance
cov_type: 'global' # Covariance specification. Empirical_true computes the empirical covariance over the true labels of the training set and fixes it.
# Empirical_predicted computes the covariance over concepts predicted by the model's encoder ['empirical_true', 'empirical_predicted', 'global']
reg_precision: 'None' # Regularization strategy of covariance ['l1', None] if it is learned
reg_weight: 1 # Regularization strength if reg_precision is not None
data_ratio: 1 # Low ratio for debugging purposes
covariance_scaling: 8
# --------------------------
#         Policy
# --------------------------
inter_policy: 'random,prob_unc' # Comma-separated intervention policies to determine which concept to intervene. Combinable options: ['random','prob_unc']
inter_strategy: 'hard,simple_perc,emp_perc,conf_interval_optimal' 
# Comma-separated intervention strategies to determine how to perform interventions. Combinable options: ['simple_perc', 'emp_perc', 'conf_interval_optimal']
level: 0.99 # Confidence level for confidence interval based intervention strategy

