experiment_name: 'experiments' # Name of the experiment
experiment_dir: './experiments/'  # Directory to potentially save the model to

seed: 0 # Random seed
workers: 2 # Number of workers for data loading
save_model: True # Whether to save the model. Set to True for inspecting models post training [True, False]

logging:
  project: 'PSCBM' # Name of the wandb project
  mode: 'online' # Whether to log to wandb [online, offline, disabled]
  entity: "wiktorh" # Your wandb entity
  # host: "http://wandb-vogtlab.leomed.ethz.ch:46766"
  host: "https://api.wandb.ai"
