defaults: 
  - model_defaults # Inherit model_defaults arguments

# --------------------------
#         Model
# --------------------------
model: 'cbm' # Model's name (to indicate it's a baseline)
tag: 'baseline' # Model's tag for wandb logging
concept_learning: 'embedding' # Concept Embedding Model baseline                

# --------------------------
#         Policy
# --------------------------
inter_policy: 'random,prob_unc' # Comma-separated intervention policies to determine which concept to intervene. Combinable options: ['random','prob_unc']
inter_strategy: 'hard' # Interventions are performed by setting the concept to 0 or 1

# --------------------------
#         Training
# --------------------------
training_mode: 'joint' # Optimization method of CEMs is joint training
embedding_size: 16 # Embedding size per concept for CEMs
